# Generated by Django 4.2.26 on 2025-12-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
