# Generated by Django 4.2.26 on 2025-12-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_diary', '0002_alter_food_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
